# PyScripts/Makefile

PYTHON = python3
VENV = ../.venv

.PHONY: run clean

run:
	@echo "Activating virtual environment and running FormVisualizer.py..."
	@. $(VENV)/bin/activate && $(PYTHON) FormVisualizer.py
